"use client";
import { useState } from "react";
import Sidebar from "@/components/Sidebar";
import TopBar from "@/components/TopBar";
import { SAMPLE_REPORTS } from "@/lib/api";
import { Report } from "@/types";
import { FileText, Download, ChevronDown, ChevronUp, AlertTriangle, CheckCircle, AlertCircle, Calendar, MapPin, User, TrendingUp } from "lucide-react";

const LEVEL_STYLE = {
  High:   { badge: "bg-red-500/15 text-red-400 border-red-500/30",     icon: AlertTriangle, bar: "#ef4444" },
  Medium: { badge: "bg-yellow-500/15 text-yellow-400 border-yellow-500/30", icon: AlertCircle,   bar: "#f59e0b" },
  Low:    { badge: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30", icon: CheckCircle, bar: "#10b981" },
};

const FEATURE_LABELS: Record<string, string> = {
  HR: "Heart Rate", O2Sat: "O₂ Saturation", Temp: "Temperature",
  SBP: "Systolic BP", MAP: "Mean Art. Press.", Resp: "Respiration",
};

const STATUS_STYLE = {
  high:   "bg-red-500/15 text-red-400 border-red-500/30",
  low:    "bg-yellow-500/15 text-yellow-400 border-yellow-500/30",
  normal: "bg-emerald-500/15 text-emerald-400 border-emerald-500/30",
};

export default function ReportsPage() {
  const [expanded, setExpanded] = useState<string | null>(null);
  const [filter, setFilter]     = useState<"All" | "High" | "Medium" | "Low">("All");

  const filtered = SAMPLE_REPORTS.filter(r =>
    filter === "All" ? true : r.riskLevel === filter
  );

  const handleDownload = (report: Report) => {
    const content = `
SEPSISGUARD — CLINICAL RISK REPORT
====================================
Report ID   : ${report.id}
Patient     : ${report.patientName} (${report.patientId})
Ward        : ${report.ward}
Generated   : ${report.generatedAt}

RISK ASSESSMENT
---------------
Risk Level  : ${report.riskLevel}
Risk Score  : ${report.riskPercent.toFixed(1)}%

VITALS AT TIME OF ASSESSMENT
-----------------------------
Heart Rate       : ${report.vitals.HR} bpm
O₂ Saturation    : ${report.vitals.O2Sat} %
Temperature      : ${report.vitals.Temp} °C
Systolic BP      : ${report.vitals.SBP} mmHg
Mean Art. Press. : ${report.vitals.MAP} mmHg
Respiration Rate : ${report.vitals.Resp} breaths/min

VITAL CONTRIBUTIONS
-------------------
${report.contributors.map(c => `${FEATURE_LABELS[c.feature] ?? c.feature}: ${c.value} (${c.status}) — ${(c.contribution * 100).toFixed(0)}% contribution`).join("\n")}

CLINICAL RECOMMENDATION
------------------------
${report.recommendation}

====================================
Generated by SepsisGuard AI System
    `.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement("a");
    a.href     = url;
    a.download = `SepsisGuard_${report.id}_${report.patientName.replace(" ", "_")}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="flex min-h-screen bg-gray-50 dark:bg-gray-950 text-gray-900 dark:text-white transition-colors duration-200">
      <Sidebar />
      <div className="flex-1 flex flex-col min-w-0">
        <TopBar />
        <main className="flex-1 p-6 overflow-auto">
          {/* Header */}
          <div className="flex items-center justify-between mb-6">
            <div>
              <h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-3">
                <FileText className="w-6 h-6 text-blue-400" />
                Clinical Reports
              </h1>
              <p className="text-gray-500 text-sm mt-1">{SAMPLE_REPORTS.length} reports generated</p>
            </div>
            <div className="flex gap-2">
              {(["All", "High", "Medium", "Low"] as const).map(f => (
                <button key={f} onClick={() => setFilter(f)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-all ${
                    filter === f
                      ? "bg-blue-500/20 text-blue-400 border-blue-500/40"
                      : "bg-gray-800 text-gray-400 border-gray-700 hover:border-gray-600"
                  }`}>{f}</button>
              ))}
            </div>
          </div>

          {/* Summary */}
          <div className="grid grid-cols-3 gap-4 mb-6">
            {(["High", "Medium", "Low"] as const).map(level => {
              const count = SAMPLE_REPORTS.filter(r => r.riskLevel === level).length;
              const style = LEVEL_STYLE[level];
              const Icon  = style.icon;
              return (
                <div key={level} className={`rounded-xl p-4 border ${style.badge}`}>
                  <div className="flex items-center gap-2 mb-1">
                    <Icon className="w-4 h-4" />
                    <span className="text-sm font-medium">{level} Risk</span>
                  </div>
                  <p className="text-2xl font-bold">{count} reports</p>
                </div>
              );
            })}
          </div>

          {/* Report cards */}
          <div className="space-y-3">
            {filtered.map(report => {
              const style = LEVEL_STYLE[report.riskLevel];
              const Icon  = style.icon;
              const isExp = expanded === report.id;

              return (
                <div key={report.id} className="bg-white dark:bg-gray-900 border border-gray-200 dark:border-gray-800 rounded-2xl overflow-hidden">
                  <div className="flex items-center gap-4 p-4">
                    <div className="w-10 h-10 rounded-xl bg-blue-500/10 border border-blue-500/20 flex items-center justify-center flex-shrink-0">
                      <FileText className="w-5 h-5 text-blue-400" />
                    </div>

                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <p className="text-white font-semibold">{report.patientName}</p>
                        <span className="text-gray-600 text-xs">{report.id}</span>
                        <span className={`text-xs px-2 py-0.5 rounded-full border font-medium ${style.badge}`}>
                          <Icon className="w-3 h-3 inline mr-1" />{report.riskLevel} Risk
                        </span>
                      </div>
                      <div className="flex items-center gap-3 mt-1 text-xs text-gray-600">
                        <span className="flex items-center gap-1"><MapPin className="w-3 h-3" />{report.ward}</span>
                        <span className="flex items-center gap-1"><Calendar className="w-3 h-3" />{report.generatedAt}</span>
                        <span className="flex items-center gap-1"><User className="w-3 h-3" />{report.patientId}</span>
                      </div>
                    </div>

                    <div className="flex items-center gap-3">
                      <div className="text-right">
                        <p className="text-2xl font-bold text-white font-mono">{report.riskPercent.toFixed(1)}%</p>
                        <p className="text-gray-600 text-xs">Risk Score</p>
                      </div>

                      <button onClick={() => handleDownload(report)}
                        className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-blue-500/15 text-blue-400 border border-blue-500/30 hover:bg-blue-500/25 text-xs font-medium transition-all">
                        <Download className="w-3.5 h-3.5" /> Export
                      </button>

                      <button onClick={() => setExpanded(isExp ? null : report.id)}
                        className="p-2 rounded-lg text-gray-500 hover:text-white hover:bg-gray-800 transition-all">
                        {isExp ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                      </button>
                    </div>
                  </div>

                  {/* Expanded report detail */}
                  {isExp && (
                    <div className="border-t border-gray-200 dark:border-gray-800 p-4 bg-gray-50/50 dark:bg-gray-950/50 space-y-4">
                      {/* Vitals grid */}
                      <div>
                        <p className="text-xs text-gray-500 font-medium uppercase tracking-wider mb-3">Vitals at Assessment</p>
                        <div className="grid grid-cols-3 sm:grid-cols-6 gap-3">
                          {Object.entries(report.vitals).map(([key, val]) => (
                            <div key={key} className="bg-gray-100 dark:bg-gray-800/50 border border-gray-200 dark:border-gray-700/50 rounded-xl p-3 text-center">
                              <p className="text-gray-900 dark:text-white font-bold font-mono text-lg">{val}</p>
                              <p className="text-gray-500 text-xs">{FEATURE_LABELS[key] ?? key}</p>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Risk bar */}
                      <div>
                        <div className="flex justify-between text-xs text-gray-500 mb-1">
                          <span>Risk Score</span>
                          <span className="font-mono text-white">{report.riskPercent.toFixed(1)}%</span>
                        </div>
                        <div className="h-3 rounded-full bg-gray-200 dark:bg-gray-800 overflow-hidden">
                          <div className="h-full rounded-full transition-all duration-700"
                            style={{ width: `${report.riskPercent}%`, background: style.bar }} />
                        </div>
                      </div>

                      {/* Contributors */}
                      <div>
                        <p className="text-xs text-gray-500 font-medium uppercase tracking-wider mb-3">Vital Contributions</p>
                        <div className="space-y-2">
                          {report.contributors.map(c => (
                            <div key={c.feature} className="space-y-1">
                              <div className="flex items-center justify-between text-xs">
                                <div className="flex items-center gap-2">
                                  <span className="text-gray-300 w-36">{FEATURE_LABELS[c.feature] ?? c.feature}</span>
                                  <span className={`px-1.5 py-0.5 rounded border text-xs ${STATUS_STYLE[c.status]}`}>{c.status}</span>
                                </div>
                                <div className="flex items-center gap-3 text-gray-400">
                                  <span className="font-mono">{c.value}</span>
                                  <span className="text-gray-600">({c.normal_range})</span>
                                  <span className="text-gray-300 font-semibold w-10 text-right">{(c.contribution * 100).toFixed(0)}%</span>
                                </div>
                              </div>
                              <div className="h-1.5 bg-gray-200 dark:bg-gray-800 rounded-full overflow-hidden">
                                <div className="h-full rounded-full transition-all duration-700"
                                  style={{ width: `${c.contribution * 100}%`, background: c.status === "normal" ? "#10b981" : c.contribution > 0.6 ? "#ef4444" : "#f59e0b" }} />
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>

                      {/* Recommendation */}
                      <div className={`rounded-xl p-4 border ${style.badge}`}>
                        <div className="flex items-center gap-2 mb-2">
                          <TrendingUp className="w-4 h-4" />
                          <p className="text-sm font-semibold">Clinical Recommendation</p>
                        </div>
                        <p className="text-sm opacity-90">{report.recommendation}</p>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </main>
      </div>
    </div>
  );
}
